<a href="https://colab.research.google.com/github/LNBMS/dev/blob/main/interacting_with_web_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import requests
import pandas as pd
import matplotlib.pyplot as plt

define api endpoint

In [2]:
url = "https://jsonplaceholder.typicode.com/posts"

print(url)

https://jsonplaceholder.typicode.com/posts

send a get request

In [3]:
response = requests.get(url, timeout=15)

print(response.status_code)

200

Read the JSON response

In [4]:
posts = response.json()

print(type(posts))
print(len(posts))
print(posts[0])

<class 'list'>
100
{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

In [5]:
print(posts[0])

{'userId': 1, 'id': 1, 'title': 'sunt aut facere repellat provident occaecati excepturi optio reprehenderit', 'body': 'quia et suscipit\nsuscipit recusandae consequuntur expedita et cum\nreprehenderit molestiae ut ut quas totam\nnostrum rerum est autem sunt rem eveniet architecto'}

create a dataframe

In [6]:
df = pd.DataFrame(posts)

print(df.head())

   userId  id                                              title  \
0       1   1  sunt aut facere repellat provident occaecati e...
1       1   2                                       qui est esse
2       1   3  ea molestias quasi exercitationem repellat qui...
3       1   4                               eum et est occaecati
4       1   5                                 nesciunt quas odio

                                                body
0  quia et suscipit\nsuscipit recusandae consequu...
1  est rerum tempore vitae\nsequi sint nihil repr...
2  et iusto sed quo iure\nvoluptatem occaecati om...
3  ullam et saepe reiciendis voluptatem adipisci\...
4  repudiandae veniam quaerat sunt sed\nalias aut...

explore the dataset

In [7]:
df.shape

(100, 4)

In [8]:
df.columns

Index(['userId', 'id', 'title', 'body'], dtype='object')

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   userId  100 non-null    int64
 1   id      100 non-null    int64
 2   title   100 non-null    object
 3   body    100 non-null    object
dtypes: int64(2), object(2)
memory usage: 3.3+ KB

In [10]:
df.isnull().sum()

userId    0
id        0
title     0
body      0
dtype: int64

In [11]:
df["userId"].value_counts().sort_index()

userId
1     10
2     10
3     10
4     10
5     10
6     10
7     10
8     10
9     10
10    10
Name: count, dtype: int64

In [12]:
df[["id", "userId", "title"]].head(10)

   id  userId                                              title
0   1       1  sunt aut facere repellat provident occaecati e...
1   2       1                                       qui est esse
2   3       1  ea molestias quasi exercitationem repellat qui...
3   4       1                               eum et est occaecati
4   5       1                                 nesciunt quas odio
5   6       1                 dolorem eum magni eos aperiam quia
6   7       1                               magnam facilis autem
7   8       1                           dolorem dolore est ipsam
8   9       1  nesciunt iure omnis dolorem tempora et accusan...
9  10       1                        optio molestias id quia eum

In [13]:
user_1_posts = df[df["userId"] == 1]

print(user_1_posts)

   userId  id                                              title  \
0       1   1  sunt aut facere repellat provident occaecati e...
1       1   2                                       qui est esse
2       1   3  ea molestias quasi exercitationem repellat qui...
3       1   4                               eum et est occaecati
4       1   5                                 nesciunt quas odio
5       1   6                 dolorem eum magni eos aperiam quia
6       1   7                               magnam facilis autem
7       1   8                           dolorem dolore est ipsam
8       1   9  nesciunt iure omnis dolorem tempora et accusan...
9       1  10                        optio molestias id quia eum

                                                body
0  quia et suscipit\nsuscipit recusandae consequu...
1  est rerum tempore vitae\nsequi sint nihil repr...
2  et iusto sed quo iure\nvoluptatem occaecati om...
3  ullam et saepe reiciendis voluptatem adipisci\...
4  repudiandae veniam quaerat sunt sed\nalias aut...
5  ut aspernatur corporis harum nihil quis provid...
6  dolore placeat quibusdam ea quo vitae\nmagni q...
7  dignissimos aperiam dolorem qui eum\nfacilis q...
8  consectetur animi nesciunt iure dolore\nenim q...
9  quo et expedita modi cum officia vel magni\ndo...

In [14]:
keyword = "qui"

matches = df[
    df["title"].str.contains(keyword, case=False, na=False)
]

print(matches[["id", "userId", "title"]])

    id  userId                                              title
1    2       1                                       qui est esse
2    3       1  ea molestias quasi exercitationem repellat qui...
5    6       1                 dolorem eum magni eos aperiam quia
9   10       1                        optio molestias id quia eum
10  11       2                   et ea vero quia laudantium autem
11  12       2              in quibusdam tempore odit est dolorem
18  19       2          adipisci placeat illum aut reiciendis qui
20  21       3  asperiores ea ipsam voluptatibus modi minima q...
21  22       3          dolor sint quo a velit explicabo quia nam
24  25       3                      rem alias distinctio quo quis
25  26       3                           est et quae odit qui non
27  28       3    delectus ullam et corporis nulla voluptas sequi
30  31       4            ullam ut quidem id aut vel consequuntur
31  32       4                      doloremque illum aliquid sunt
32  33       4                    qui explicabo molestiae dolorem
46  47       5                  quibusdam cumque rem aut deserunt
49  50       5  repellendus qui recusandae incidunt voluptates...
50  51       6  soluta aliquam aperiam consequatur illo quis v...
51  52       6  qui enim et consequuntur quia animi quis volup...
53  54       6         sit asperiores ipsam eveniet odio non quia
55  56       6                     qui et at rerum necessitatibus
58  59       6  qui commodi dolor at maiores et quis id accusa...
59  60       6  consequatur placeat omnis quisquam quia repreh...
61  62       7                               beatae enim quia vel
66  67       7        aliquid eos sed fuga est maxime repellendus
67  68       7       odio quis facere architecto reiciendis optio
72  73       8  consequuntur deleniti eos quia temporibus ab a...
78  79       8  pariatur consequatur quia magnam autem omnis n...
85  86       9                         placeat quia et porro iste
86  87       9                         nostrum quis quasi placeat
88  89       9           sint soluta et vel magnam aut ut sed qui
93  94      10                qui qui voluptates illo iste minima
95  96      10  quaerat velit veniam amet cupiditate aut numqu...